crawlings/urls.py
from django.urls import path
from . import views

app_name = 'crawlings'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('find/', views.find, name='find'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('ai_analyze/', views.ai_analyze, name='ai_analyze')
]

finance_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crawlings/', include('crawlings.urls')),
]

crawlings/models.py
from django.db import models

# Create your models here.
class Crawlings(models.Model):
    title = models.CharField(max_length=20)
    code = models.CharField(max_length=7)
    comment = models.TextField()
    updated_at = models.DateField(auto_now_add=True)

crawlings/forms.py
from django import forms
from .models import Crawlings

class CrawlingForm(forms.ModelForm):
    class Meta():
        model = Crawlings
        fields = '__all__'

crawlings/views.py
from django.shortcuts import render, redirect
from .models import Crawlings
from .utils import crawl_toss_comments_by_name, get_comment_form_OpenAI

# Create your views here.
def index(request):
    company_info = request.GET.get('title')
    context = {
        'company_info': company_info,
    }
    return render(request, 'crawlings/index.html', context)

def find(request):
    if request.method == 'POST':
        stock_name = request.POST.get('title')

        # 크롤링 실행
        stock_name, code, comments = crawl_toss_comments_by_name(stock_name)

        # DB 저장
        for c in comments:
            Crawlings.objects.create(
                title = stock_name,
                code= code,
                comment=c['comment'],
            )
        
        # 3. 저장한 결과 다시 읽기
        results = Crawlings.objects.filter(title=stock_name).order_by('-updated_at')

        # 분석 결과 호출
        report = analyze_comments_by_title(stock_name)

        return render(request, 'crawlings/index.html', {
            'company_info': {
                'title': stock_name,
                'code': code,
                'comments': results,
            },
            'report': report,
        })
    else:
        return render(request, 'crawlings/index.html')

def delete_comment(request, pk):
    if request.method == 'POST':
        title = request.POST.get('title')
        comment = Crawlings.objects.get(pk=pk)
        comment.delete()

        results = Crawlings.objects.filter(title=title)
        code = results.first().code if results.exists() else '000000'
        return render(request, 'crawlings/index.html', {
            'company_info': {
                'title': title,
                'code': code,
                'comments': results,
            }
        })
    else:
        return redirect('crawlings:index')
    

def analyze_comments_by_title(title):
    comments_qs = Crawlings.objects.filter(title=title).order_by('-updated_at')
    comments = [c.comment for c in comments_qs]
    return get_comment_form_OpenAI(comments)

    
def ai_analyze(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        comments_qs = Crawlings.objects.filter(title=title).order_by('-updated_at')
        code = comments_qs.first().code if comments_qs.exists() else "000000"
        comments = [c.comment for c in comments_qs]

        report = get_comment_form_OpenAI(comments)

        return render(request, 'crawlings/index.html', {
            'company_info': {
                'title': title,
                'code': code,
                'comments': comments_qs,
            },
            'report': report
        })
    else:
        return redirect('crawlings:index')

crawlings/templates/crawlings/index.html
{% extends "base.html" %} 

{% block content %}
<p>주식에 대한, 투자자들의 목소리</p>
<h1>주식 댓글 분석기</h1>

<form action="{% url "crawlings:find" %}" method="POST">
  {% csrf_token %}
  <div>
    <label for="title">회사 이름을 입력하세요: </label>
    <input type="text" name="title" id="title" />
    <input type="submit" value="검색" />
  </div>
</form>

{% if company_info %} 
<h2>{{ company_info.title }} ({{ company_info.code }})</h2>


  <h3>수집된 댓글:</h3>
  {% for item in company_info.comments %}
  <ul>
    <div style="display: flex; align-items: center; gap: 10px; margin-bottom:8px;">
        <li stype="list-style: none;">{{ item.comment }}</li>
        <form action="{% url "crawlings:delete_comment" item.pk %}" method="POST" style="margin: 0;">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ company_info.title }}">
            <input type="submit" value="삭제">
        </form>
    </div>
  </ul>
  {% endfor %}

  <h3>'gpt-4o-mini' 분석:</h3>
  {% if report %}
  <h3>GPT 분석 결과:</h3>
  <p>{{ report }}</p>
  {% endif %}
{% else %}
<h3>일치하는 회사 이름이 없습니다.</h3>

{% endif %} 
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>